### ISSUE TITLE
Remove Microsoft. from namespaces in docs 

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fsharp-core-api-docs#4]
We want 

    FSharp.Collection.List

not

    Microsoft.FSharp.Collection.List

**Comment by ymassad** [comment]
I came here because based on the docs, I thought the FSharpFunc type lives in FSharp.Core. But when I looked it up in the code, it was in Microsoft.FSharp.Core.FSharpFunc. Will the FSharpFunc type be moved to FSharp.Core? Or such a move is only from the docs perspective?

My question basically is can I assume that FSharpFunc's fullname will always be "Microsoft.FSharp.Core.FSharpFunc"?

If not, is there a way to ask the runtime about the location of FSharpFunc?

**Comment by dsyme** [comment]
> My question basically is can I assume that FSharpFunc's fullname will always be "Microsoft.FSharp.Core.FSharpFunc"?

Yes you can.  The type is in the FSharp.Core.dll and the F# compiler has a rule that says you can simply use "open FSharp.Core" (which is actually done implicitly anyway).

In the actualy compiled DLL and reflection form the name "Microsoft.FSharp.Core.FSharpFunc" is kept for the purposes of binary compatibility.

**Comment by ymassad** [comment]
Thanks, @dsyme
